test: main.cpp
	g++ -std=c++11 main.cpp  dnn_opencv.cpp -o test `pkg-config opencv --cflags --libs`
debug: main.cpp
	g++ -g -std=c++11 main.cpp  dnn_opencv.cpp -o test `pkg-config opencv --cflags --libs`
